version: '3.9'
services:
  app:
    build: .
    container_name: insightfixer-app
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    env_file:
      - .env
    environment:
      - QDRANT_HOST=${QDRANT_HOST}
      - QDRANT_PORT=${QDRANT_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    restart: unless-stopped
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
